FROM nginx:1.21.6-alpine
LABEL maintainer="DIGILOCKER"
LABEL version="1.0"
ENV TZ="Asia/Kolkata"

# Install packages
RUN apk --no-cache add bash php7 php7-fpm php7-json php7-openssl php7-curl php7-zlib php7-mbstring php7-bcmath supervisor php7-redis php7-opcache tzdata

# Config PHP
RUN sed -i "s/;date.timezone =.*/date.timezone = Asia\/Kolkata/g" /etc/php7/php.ini \
    && sed -i "s/upload_max_filesize =.*/upload_max_filesize = 250M/g" /etc/php7/php.ini \
    && sed -i "s/memory_limit = 128M/memory_limit = 512M/g" /etc/php7/php.ini \
    && sed -i "s/post_max_size =.*/post_max_size = 250M/g" /etc/php7/php.ini \
    && sed -i "s/user = nobody/user = root/g" /etc/php7/php-fpm.d/www.conf \
    && sed -i "s/group = nobody/group = root/g" /etc/php7/php-fpm.d/www.conf \
    && sed -i "s/listen.owner = nobody/listen.owner = root/g" /etc/php7/php-fpm.d/www.conf \
    && sed -i "s/listen.group = nobody/listen.group = root/g" /etc/php7/php-fpm.d/www.conf \
    && sed -i "s/listen.group = nobody/listen.group = root/g" /etc/php7/php-fpm.d/www.conf \
    && cp /usr/share/zoneinfo/Asia/Kolkata /etc/localtime && echo Asia/Kolkata > /etc/timezone \
    && apk del tzdata

# Copy nginx config
RUN rm -f /etc/nginx/conf.d/default.conf
COPY config/nginx.conf /etc/nginx/nginx.conf
COPY config/api.conf /etc/nginx/sites-enabled/default
COPY config/upstream.conf /etc/nginx/upstream.conf

# Configure PHP-FPM
COPY config/fpm-pool.conf /etc/php7/php-fpm.d/my_custom.conf

# Configure supervisord
COPY config/supervisord.conf /etc/supervisor/conf.d/supervisord.conf
COPY config/supervisord.conf /etc/supervisord.conf
COPY config/php.ini /etc/php7/php.ini
# Add application
WORKDIR /var/www
#COPY src_code/ /var/www/

EXPOSE 80 
CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]